### ISSUE TITLE
React Native entfernen

### ISSUE THREAD

**Issue by mrgrauel** [snabble/iOS-SDK#45]
Alle Abhängigkeiten für React Native können entfernt werden

* implicitNavigation boolean entfernen
* navigationDelegates entfernen

**Comment by mrgrauel** [comment]
@gereons fallen wir noch weitere Sachen ein?

**Comment by gereons** [comment]
`ReactNativeWrapper` und alle seine Witnesses sollten noch weg, plus alles was es nur gibt oder öffentlich ist damit es von da aus benutzt werden kann.
